added basic rules
ibexa/eslint-config-ibexa pull request #1
Opened 2021-08-30 12:08 UTC by GrabowskiM

2021-08-30 14:07 UTC, lucasOsti requested changes

2021-08-30 14:07 UTC, lucasOsti commented on index.js
>  };
new line :D

2021-08-31 06:53 UTC, tischsoic approved these changes

2021-08-31 06:53 UTC, dew326 approved these changes

2021-08-31 06:56 UTC, merged